#!/usr/bin/env python3
"""Flagfetch source code"""

from typing import AnyStr
import sys

# Settings
## Used to print debug output.
DEBUG = True


# Source code begins here.
def debug(to_print: AnyStr) -> None:
	"""Prints any data to stderr if DEBUG variable is set.

	Args:
		to_print: Data to print. Should be any string
	"""
	if DEBUG:
		sys.stderr.write(to_print)


def main() -> None:
	print_system_flags()


if __name__ == "__main__":
	main()
