line-length = 80
indent-width = 4
target-version = "py38"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true

[lint]
select = ["E4", "E7", "E9", "F", "B"]
ignore = ["E501"]
unfixable = ["B"]

